/* Automatically generated by po2tbl.sed from NF-chat.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"X-Chat", 2},
  {"New Server Tab..", 3},
  {"New Server Window..", 4},
  {"New Channel Tab..", 5},
  {"New Channel Window..", 6},
  {"Close", 7},
  {"Quit", 8},
  {"Windows", 9},
  {"Flush Buffer", 10},
  {"Save Buffer..", 11},
  {"User Modes", 12},
  {"Invisible", 13},
  {"Receive Wallops", 14},
  {"Receive Server Notices", 15},
  {"Marked Away", 16},
  {"Auto ReJoin on Kick", 17},
  {"Auto ReConnect to Server", 18},
  {"Never-give-up ReConnect", 19},
  {"Auto Open Dialog Windows", 20},
  {"Auto Accept DCC Chat", 21},
  {"Auto Accept DCC Send", 22},
  {"Settings", 23},
  {"User Commands..", 24},
  {"CTCP Replies..", 25},
  {"Userlist Buttons..", 26},
  {"Userlist Popup..", 27},
  {"Replace..", 28},
  {"URL Handlers..", 29},
  {"Edit Event Texts..", 30},
  {"Edit Key Bindings..", 31},
  {"Select theme..", 32},
  {"Reload Settings", 33},
  {"Save Settings now", 34},
  {"Save Settings on exit", 35},
  {"Scripts & Plugins", 36},
  {"Load Perl Script..", 37},
  {"Unload All Scripts", 38},
  {"Perl List", 39},
  {"Help", 40},
  {"Help..", 41},
  {"X-Chat Homepage..", 42},
  {"Online Docs..", 43},
};

int _msg_tbl_length = 43;
