/* Automatically generated by po2tbl.sed from NF-chat.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Help", 2},
  {"Help..", 3},
  {"X-Chat Homepage..", 4},
  {"Online Docs..", 5},
};

int _msg_tbl_length = 5;
